// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/config': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config').default>>>>
    }
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/user/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}