
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'EssentialLink': typeof import("../components/EssentialLink.vue")['default']
    'ExampleComponent': typeof import("../components/ExampleComponent.vue")['default']
    'ExampleList': typeof import("../components/ExampleList.vue")['default']
    'MenuRedirect': typeof import("../components/MenuRedirect.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'QAjaxBar': typeof import("quasar")['QAjaxBar']
    'QAvatar': typeof import("quasar")['QAvatar']
    'QBadge': typeof import("quasar")['QBadge']
    'QBanner': typeof import("quasar")['QBanner']
    'QBar': typeof import("quasar")['QBar']
    'QBreadcrumbs': typeof import("quasar")['QBreadcrumbs']
    'QBreadcrumbsEl': typeof import("quasar")['QBreadcrumbsEl']
    'QBtn': typeof import("quasar")['QBtn']
    'QBtnDropdown': typeof import("quasar")['QBtnDropdown']
    'QBtnGroup': typeof import("quasar")['QBtnGroup']
    'QBtnToggle': typeof import("quasar")['QBtnToggle']
    'QCard': typeof import("quasar")['QCard']
    'QCardActions': typeof import("quasar")['QCardActions']
    'QCardSection': typeof import("quasar")['QCardSection']
    'QCarousel': typeof import("quasar")['QCarousel']
    'QCarouselControl': typeof import("quasar")['QCarouselControl']
    'QCarouselSlide': typeof import("quasar")['QCarouselSlide']
    'QChatMessage': typeof import("quasar")['QChatMessage']
    'QCheckbox': typeof import("quasar")['QCheckbox']
    'QChip': typeof import("quasar")['QChip']
    'QCircularProgress': typeof import("quasar")['QCircularProgress']
    'QColor': typeof import("quasar")['QColor']
    'QDate': typeof import("quasar")['QDate']
    'QDialog': typeof import("quasar")['QDialog']
    'QDrawer': typeof import("quasar")['QDrawer']
    'QEditor': typeof import("quasar")['QEditor']
    'QExpansionItem': typeof import("quasar")['QExpansionItem']
    'QFab': typeof import("quasar")['QFab']
    'QFabAction': typeof import("quasar")['QFabAction']
    'QField': typeof import("quasar")['QField']
    'QFile': typeof import("quasar")['QFile']
    'QFooter': typeof import("quasar")['QFooter']
    'QForm': typeof import("quasar")['QForm']
    'QFormChildMixin': typeof import("quasar")['QFormChildMixin']
    'QHeader': typeof import("quasar")['QHeader']
    'QIcon': typeof import("quasar")['QIcon']
    'QImg': typeof import("quasar")['QImg']
    'QInfiniteScroll': typeof import("quasar")['QInfiniteScroll']
    'QInnerLoading': typeof import("quasar")['QInnerLoading']
    'QInput': typeof import("quasar")['QInput']
    'QIntersection': typeof import("quasar")['QIntersection']
    'QItem': typeof import("quasar")['QItem']
    'QItemLabel': typeof import("quasar")['QItemLabel']
    'QItemSection': typeof import("quasar")['QItemSection']
    'QList': typeof import("quasar")['QList']
    'QKnob': typeof import("quasar")['QKnob']
    'QLayout': typeof import("quasar")['QLayout']
    'QLinearProgress': typeof import("quasar")['QLinearProgress']
    'QMarkupTable': typeof import("quasar")['QMarkupTable']
    'QMenu': typeof import("quasar")['QMenu']
    'QNoSsr': typeof import("quasar")['QNoSsr']
    'QOptionGroup': typeof import("quasar")['QOptionGroup']
    'QPage': typeof import("quasar")['QPage']
    'QPageContainer': typeof import("quasar")['QPageContainer']
    'QPageScroller': typeof import("quasar")['QPageScroller']
    'QPageSticky': typeof import("quasar")['QPageSticky']
    'QPagination': typeof import("quasar")['QPagination']
    'QParallax': typeof import("quasar")['QParallax']
    'QPopupEdit': typeof import("quasar")['QPopupEdit']
    'QPopupProxy': typeof import("quasar")['QPopupProxy']
    'QPullToRefresh': typeof import("quasar")['QPullToRefresh']
    'QRadio': typeof import("quasar")['QRadio']
    'QRange': typeof import("quasar")['QRange']
    'QRating': typeof import("quasar")['QRating']
    'QResizeObserver': typeof import("quasar")['QResizeObserver']
    'QResponsive': typeof import("quasar")['QResponsive']
    'QScrollArea': typeof import("quasar")['QScrollArea']
    'QScrollObserver': typeof import("quasar")['QScrollObserver']
    'QSelect': typeof import("quasar")['QSelect']
    'QSeparator': typeof import("quasar")['QSeparator']
    'QSkeleton': typeof import("quasar")['QSkeleton']
    'QSlideItem': typeof import("quasar")['QSlideItem']
    'QSlideTransition': typeof import("quasar")['QSlideTransition']
    'QSlider': typeof import("quasar")['QSlider']
    'QSpace': typeof import("quasar")['QSpace']
    'QSpinner': typeof import("quasar")['QSpinner']
    'QSpinnerAudio': typeof import("quasar")['QSpinnerAudio']
    'QSpinnerBall': typeof import("quasar")['QSpinnerBall']
    'QSpinnerBars': typeof import("quasar")['QSpinnerBars']
    'QSpinnerBox': typeof import("quasar")['QSpinnerBox']
    'QSpinnerClock': typeof import("quasar")['QSpinnerClock']
    'QSpinnerComment': typeof import("quasar")['QSpinnerComment']
    'QSpinnerCube': typeof import("quasar")['QSpinnerCube']
    'QSpinnerDots': typeof import("quasar")['QSpinnerDots']
    'QSpinnerFacebook': typeof import("quasar")['QSpinnerFacebook']
    'QSpinnerGears': typeof import("quasar")['QSpinnerGears']
    'QSpinnerGrid': typeof import("quasar")['QSpinnerGrid']
    'QSpinnerHearts': typeof import("quasar")['QSpinnerHearts']
    'QSpinnerHourglass': typeof import("quasar")['QSpinnerHourglass']
    'QSpinnerInfinity': typeof import("quasar")['QSpinnerInfinity']
    'QSpinnerIos': typeof import("quasar")['QSpinnerIos']
    'QSpinnerOrbit': typeof import("quasar")['QSpinnerOrbit']
    'QSpinnerOval': typeof import("quasar")['QSpinnerOval']
    'QSpinnerPie': typeof import("quasar")['QSpinnerPie']
    'QSpinnerPuff': typeof import("quasar")['QSpinnerPuff']
    'QSpinnerRadio': typeof import("quasar")['QSpinnerRadio']
    'QSpinnerRings': typeof import("quasar")['QSpinnerRings']
    'QSpinnerTail': typeof import("quasar")['QSpinnerTail']
    'QSplitter': typeof import("quasar")['QSplitter']
    'QStep': typeof import("quasar")['QStep']
    'QStepper': typeof import("quasar")['QStepper']
    'QStepperNavigation': typeof import("quasar")['QStepperNavigation']
    'QTabPanel': typeof import("quasar")['QTabPanel']
    'QTabPanels': typeof import("quasar")['QTabPanels']
    'QTable': typeof import("quasar")['QTable']
    'QTd': typeof import("quasar")['QTd']
    'QTh': typeof import("quasar")['QTh']
    'QTr': typeof import("quasar")['QTr']
    'QRouteTab': typeof import("quasar")['QRouteTab']
    'QTab': typeof import("quasar")['QTab']
    'QTabs': typeof import("quasar")['QTabs']
    'QTime': typeof import("quasar")['QTime']
    'QTimeline': typeof import("quasar")['QTimeline']
    'QTimelineEntry': typeof import("quasar")['QTimelineEntry']
    'QToggle': typeof import("quasar")['QToggle']
    'QToolbar': typeof import("quasar")['QToolbar']
    'QToolbarTitle': typeof import("quasar")['QToolbarTitle']
    'QTooltip': typeof import("quasar")['QTooltip']
    'QTree': typeof import("quasar")['QTree']
    'QUploader': typeof import("quasar")['QUploader']
    'QUploaderAddTrigger': typeof import("quasar")['QUploaderAddTrigger']
    'QVideo': typeof import("quasar")['QVideo']
    'QVirtualScroll': typeof import("quasar")['QVirtualScroll']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyEssentialLink': typeof import("../components/EssentialLink.vue")['default']
    'LazyExampleComponent': typeof import("../components/ExampleComponent.vue")['default']
    'LazyExampleList': typeof import("../components/ExampleList.vue")['default']
    'LazyMenuRedirect': typeof import("../components/MenuRedirect.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyQAjaxBar': typeof import("quasar")['QAjaxBar']
    'LazyQAvatar': typeof import("quasar")['QAvatar']
    'LazyQBadge': typeof import("quasar")['QBadge']
    'LazyQBanner': typeof import("quasar")['QBanner']
    'LazyQBar': typeof import("quasar")['QBar']
    'LazyQBreadcrumbs': typeof import("quasar")['QBreadcrumbs']
    'LazyQBreadcrumbsEl': typeof import("quasar")['QBreadcrumbsEl']
    'LazyQBtn': typeof import("quasar")['QBtn']
    'LazyQBtnDropdown': typeof import("quasar")['QBtnDropdown']
    'LazyQBtnGroup': typeof import("quasar")['QBtnGroup']
    'LazyQBtnToggle': typeof import("quasar")['QBtnToggle']
    'LazyQCard': typeof import("quasar")['QCard']
    'LazyQCardActions': typeof import("quasar")['QCardActions']
    'LazyQCardSection': typeof import("quasar")['QCardSection']
    'LazyQCarousel': typeof import("quasar")['QCarousel']
    'LazyQCarouselControl': typeof import("quasar")['QCarouselControl']
    'LazyQCarouselSlide': typeof import("quasar")['QCarouselSlide']
    'LazyQChatMessage': typeof import("quasar")['QChatMessage']
    'LazyQCheckbox': typeof import("quasar")['QCheckbox']
    'LazyQChip': typeof import("quasar")['QChip']
    'LazyQCircularProgress': typeof import("quasar")['QCircularProgress']
    'LazyQColor': typeof import("quasar")['QColor']
    'LazyQDate': typeof import("quasar")['QDate']
    'LazyQDialog': typeof import("quasar")['QDialog']
    'LazyQDrawer': typeof import("quasar")['QDrawer']
    'LazyQEditor': typeof import("quasar")['QEditor']
    'LazyQExpansionItem': typeof import("quasar")['QExpansionItem']
    'LazyQFab': typeof import("quasar")['QFab']
    'LazyQFabAction': typeof import("quasar")['QFabAction']
    'LazyQField': typeof import("quasar")['QField']
    'LazyQFile': typeof import("quasar")['QFile']
    'LazyQFooter': typeof import("quasar")['QFooter']
    'LazyQForm': typeof import("quasar")['QForm']
    'LazyQFormChildMixin': typeof import("quasar")['QFormChildMixin']
    'LazyQHeader': typeof import("quasar")['QHeader']
    'LazyQIcon': typeof import("quasar")['QIcon']
    'LazyQImg': typeof import("quasar")['QImg']
    'LazyQInfiniteScroll': typeof import("quasar")['QInfiniteScroll']
    'LazyQInnerLoading': typeof import("quasar")['QInnerLoading']
    'LazyQInput': typeof import("quasar")['QInput']
    'LazyQIntersection': typeof import("quasar")['QIntersection']
    'LazyQItem': typeof import("quasar")['QItem']
    'LazyQItemLabel': typeof import("quasar")['QItemLabel']
    'LazyQItemSection': typeof import("quasar")['QItemSection']
    'LazyQList': typeof import("quasar")['QList']
    'LazyQKnob': typeof import("quasar")['QKnob']
    'LazyQLayout': typeof import("quasar")['QLayout']
    'LazyQLinearProgress': typeof import("quasar")['QLinearProgress']
    'LazyQMarkupTable': typeof import("quasar")['QMarkupTable']
    'LazyQMenu': typeof import("quasar")['QMenu']
    'LazyQNoSsr': typeof import("quasar")['QNoSsr']
    'LazyQOptionGroup': typeof import("quasar")['QOptionGroup']
    'LazyQPage': typeof import("quasar")['QPage']
    'LazyQPageContainer': typeof import("quasar")['QPageContainer']
    'LazyQPageScroller': typeof import("quasar")['QPageScroller']
    'LazyQPageSticky': typeof import("quasar")['QPageSticky']
    'LazyQPagination': typeof import("quasar")['QPagination']
    'LazyQParallax': typeof import("quasar")['QParallax']
    'LazyQPopupEdit': typeof import("quasar")['QPopupEdit']
    'LazyQPopupProxy': typeof import("quasar")['QPopupProxy']
    'LazyQPullToRefresh': typeof import("quasar")['QPullToRefresh']
    'LazyQRadio': typeof import("quasar")['QRadio']
    'LazyQRange': typeof import("quasar")['QRange']
    'LazyQRating': typeof import("quasar")['QRating']
    'LazyQResizeObserver': typeof import("quasar")['QResizeObserver']
    'LazyQResponsive': typeof import("quasar")['QResponsive']
    'LazyQScrollArea': typeof import("quasar")['QScrollArea']
    'LazyQScrollObserver': typeof import("quasar")['QScrollObserver']
    'LazyQSelect': typeof import("quasar")['QSelect']
    'LazyQSeparator': typeof import("quasar")['QSeparator']
    'LazyQSkeleton': typeof import("quasar")['QSkeleton']
    'LazyQSlideItem': typeof import("quasar")['QSlideItem']
    'LazyQSlideTransition': typeof import("quasar")['QSlideTransition']
    'LazyQSlider': typeof import("quasar")['QSlider']
    'LazyQSpace': typeof import("quasar")['QSpace']
    'LazyQSpinner': typeof import("quasar")['QSpinner']
    'LazyQSpinnerAudio': typeof import("quasar")['QSpinnerAudio']
    'LazyQSpinnerBall': typeof import("quasar")['QSpinnerBall']
    'LazyQSpinnerBars': typeof import("quasar")['QSpinnerBars']
    'LazyQSpinnerBox': typeof import("quasar")['QSpinnerBox']
    'LazyQSpinnerClock': typeof import("quasar")['QSpinnerClock']
    'LazyQSpinnerComment': typeof import("quasar")['QSpinnerComment']
    'LazyQSpinnerCube': typeof import("quasar")['QSpinnerCube']
    'LazyQSpinnerDots': typeof import("quasar")['QSpinnerDots']
    'LazyQSpinnerFacebook': typeof import("quasar")['QSpinnerFacebook']
    'LazyQSpinnerGears': typeof import("quasar")['QSpinnerGears']
    'LazyQSpinnerGrid': typeof import("quasar")['QSpinnerGrid']
    'LazyQSpinnerHearts': typeof import("quasar")['QSpinnerHearts']
    'LazyQSpinnerHourglass': typeof import("quasar")['QSpinnerHourglass']
    'LazyQSpinnerInfinity': typeof import("quasar")['QSpinnerInfinity']
    'LazyQSpinnerIos': typeof import("quasar")['QSpinnerIos']
    'LazyQSpinnerOrbit': typeof import("quasar")['QSpinnerOrbit']
    'LazyQSpinnerOval': typeof import("quasar")['QSpinnerOval']
    'LazyQSpinnerPie': typeof import("quasar")['QSpinnerPie']
    'LazyQSpinnerPuff': typeof import("quasar")['QSpinnerPuff']
    'LazyQSpinnerRadio': typeof import("quasar")['QSpinnerRadio']
    'LazyQSpinnerRings': typeof import("quasar")['QSpinnerRings']
    'LazyQSpinnerTail': typeof import("quasar")['QSpinnerTail']
    'LazyQSplitter': typeof import("quasar")['QSplitter']
    'LazyQStep': typeof import("quasar")['QStep']
    'LazyQStepper': typeof import("quasar")['QStepper']
    'LazyQStepperNavigation': typeof import("quasar")['QStepperNavigation']
    'LazyQTabPanel': typeof import("quasar")['QTabPanel']
    'LazyQTabPanels': typeof import("quasar")['QTabPanels']
    'LazyQTable': typeof import("quasar")['QTable']
    'LazyQTd': typeof import("quasar")['QTd']
    'LazyQTh': typeof import("quasar")['QTh']
    'LazyQTr': typeof import("quasar")['QTr']
    'LazyQRouteTab': typeof import("quasar")['QRouteTab']
    'LazyQTab': typeof import("quasar")['QTab']
    'LazyQTabs': typeof import("quasar")['QTabs']
    'LazyQTime': typeof import("quasar")['QTime']
    'LazyQTimeline': typeof import("quasar")['QTimeline']
    'LazyQTimelineEntry': typeof import("quasar")['QTimelineEntry']
    'LazyQToggle': typeof import("quasar")['QToggle']
    'LazyQToolbar': typeof import("quasar")['QToolbar']
    'LazyQToolbarTitle': typeof import("quasar")['QToolbarTitle']
    'LazyQTooltip': typeof import("quasar")['QTooltip']
    'LazyQTree': typeof import("quasar")['QTree']
    'LazyQUploader': typeof import("quasar")['QUploader']
    'LazyQUploaderAddTrigger': typeof import("quasar")['QUploaderAddTrigger']
    'LazyQVideo': typeof import("quasar")['QVideo']
    'LazyQVirtualScroll': typeof import("quasar")['QVirtualScroll']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const EssentialLink: typeof import("../components/EssentialLink.vue")['default']
export const ExampleComponent: typeof import("../components/ExampleComponent.vue")['default']
export const ExampleList: typeof import("../components/ExampleList.vue")['default']
export const MenuRedirect: typeof import("../components/MenuRedirect.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const QAjaxBar: typeof import("quasar")['QAjaxBar']
export const QAvatar: typeof import("quasar")['QAvatar']
export const QBadge: typeof import("quasar")['QBadge']
export const QBanner: typeof import("quasar")['QBanner']
export const QBar: typeof import("quasar")['QBar']
export const QBreadcrumbs: typeof import("quasar")['QBreadcrumbs']
export const QBreadcrumbsEl: typeof import("quasar")['QBreadcrumbsEl']
export const QBtn: typeof import("quasar")['QBtn']
export const QBtnDropdown: typeof import("quasar")['QBtnDropdown']
export const QBtnGroup: typeof import("quasar")['QBtnGroup']
export const QBtnToggle: typeof import("quasar")['QBtnToggle']
export const QCard: typeof import("quasar")['QCard']
export const QCardActions: typeof import("quasar")['QCardActions']
export const QCardSection: typeof import("quasar")['QCardSection']
export const QCarousel: typeof import("quasar")['QCarousel']
export const QCarouselControl: typeof import("quasar")['QCarouselControl']
export const QCarouselSlide: typeof import("quasar")['QCarouselSlide']
export const QChatMessage: typeof import("quasar")['QChatMessage']
export const QCheckbox: typeof import("quasar")['QCheckbox']
export const QChip: typeof import("quasar")['QChip']
export const QCircularProgress: typeof import("quasar")['QCircularProgress']
export const QColor: typeof import("quasar")['QColor']
export const QDate: typeof import("quasar")['QDate']
export const QDialog: typeof import("quasar")['QDialog']
export const QDrawer: typeof import("quasar")['QDrawer']
export const QEditor: typeof import("quasar")['QEditor']
export const QExpansionItem: typeof import("quasar")['QExpansionItem']
export const QFab: typeof import("quasar")['QFab']
export const QFabAction: typeof import("quasar")['QFabAction']
export const QField: typeof import("quasar")['QField']
export const QFile: typeof import("quasar")['QFile']
export const QFooter: typeof import("quasar")['QFooter']
export const QForm: typeof import("quasar")['QForm']
export const QFormChildMixin: typeof import("quasar")['QFormChildMixin']
export const QHeader: typeof import("quasar")['QHeader']
export const QIcon: typeof import("quasar")['QIcon']
export const QImg: typeof import("quasar")['QImg']
export const QInfiniteScroll: typeof import("quasar")['QInfiniteScroll']
export const QInnerLoading: typeof import("quasar")['QInnerLoading']
export const QInput: typeof import("quasar")['QInput']
export const QIntersection: typeof import("quasar")['QIntersection']
export const QItem: typeof import("quasar")['QItem']
export const QItemLabel: typeof import("quasar")['QItemLabel']
export const QItemSection: typeof import("quasar")['QItemSection']
export const QList: typeof import("quasar")['QList']
export const QKnob: typeof import("quasar")['QKnob']
export const QLayout: typeof import("quasar")['QLayout']
export const QLinearProgress: typeof import("quasar")['QLinearProgress']
export const QMarkupTable: typeof import("quasar")['QMarkupTable']
export const QMenu: typeof import("quasar")['QMenu']
export const QNoSsr: typeof import("quasar")['QNoSsr']
export const QOptionGroup: typeof import("quasar")['QOptionGroup']
export const QPage: typeof import("quasar")['QPage']
export const QPageContainer: typeof import("quasar")['QPageContainer']
export const QPageScroller: typeof import("quasar")['QPageScroller']
export const QPageSticky: typeof import("quasar")['QPageSticky']
export const QPagination: typeof import("quasar")['QPagination']
export const QParallax: typeof import("quasar")['QParallax']
export const QPopupEdit: typeof import("quasar")['QPopupEdit']
export const QPopupProxy: typeof import("quasar")['QPopupProxy']
export const QPullToRefresh: typeof import("quasar")['QPullToRefresh']
export const QRadio: typeof import("quasar")['QRadio']
export const QRange: typeof import("quasar")['QRange']
export const QRating: typeof import("quasar")['QRating']
export const QResizeObserver: typeof import("quasar")['QResizeObserver']
export const QResponsive: typeof import("quasar")['QResponsive']
export const QScrollArea: typeof import("quasar")['QScrollArea']
export const QScrollObserver: typeof import("quasar")['QScrollObserver']
export const QSelect: typeof import("quasar")['QSelect']
export const QSeparator: typeof import("quasar")['QSeparator']
export const QSkeleton: typeof import("quasar")['QSkeleton']
export const QSlideItem: typeof import("quasar")['QSlideItem']
export const QSlideTransition: typeof import("quasar")['QSlideTransition']
export const QSlider: typeof import("quasar")['QSlider']
export const QSpace: typeof import("quasar")['QSpace']
export const QSpinner: typeof import("quasar")['QSpinner']
export const QSpinnerAudio: typeof import("quasar")['QSpinnerAudio']
export const QSpinnerBall: typeof import("quasar")['QSpinnerBall']
export const QSpinnerBars: typeof import("quasar")['QSpinnerBars']
export const QSpinnerBox: typeof import("quasar")['QSpinnerBox']
export const QSpinnerClock: typeof import("quasar")['QSpinnerClock']
export const QSpinnerComment: typeof import("quasar")['QSpinnerComment']
export const QSpinnerCube: typeof import("quasar")['QSpinnerCube']
export const QSpinnerDots: typeof import("quasar")['QSpinnerDots']
export const QSpinnerFacebook: typeof import("quasar")['QSpinnerFacebook']
export const QSpinnerGears: typeof import("quasar")['QSpinnerGears']
export const QSpinnerGrid: typeof import("quasar")['QSpinnerGrid']
export const QSpinnerHearts: typeof import("quasar")['QSpinnerHearts']
export const QSpinnerHourglass: typeof import("quasar")['QSpinnerHourglass']
export const QSpinnerInfinity: typeof import("quasar")['QSpinnerInfinity']
export const QSpinnerIos: typeof import("quasar")['QSpinnerIos']
export const QSpinnerOrbit: typeof import("quasar")['QSpinnerOrbit']
export const QSpinnerOval: typeof import("quasar")['QSpinnerOval']
export const QSpinnerPie: typeof import("quasar")['QSpinnerPie']
export const QSpinnerPuff: typeof import("quasar")['QSpinnerPuff']
export const QSpinnerRadio: typeof import("quasar")['QSpinnerRadio']
export const QSpinnerRings: typeof import("quasar")['QSpinnerRings']
export const QSpinnerTail: typeof import("quasar")['QSpinnerTail']
export const QSplitter: typeof import("quasar")['QSplitter']
export const QStep: typeof import("quasar")['QStep']
export const QStepper: typeof import("quasar")['QStepper']
export const QStepperNavigation: typeof import("quasar")['QStepperNavigation']
export const QTabPanel: typeof import("quasar")['QTabPanel']
export const QTabPanels: typeof import("quasar")['QTabPanels']
export const QTable: typeof import("quasar")['QTable']
export const QTd: typeof import("quasar")['QTd']
export const QTh: typeof import("quasar")['QTh']
export const QTr: typeof import("quasar")['QTr']
export const QRouteTab: typeof import("quasar")['QRouteTab']
export const QTab: typeof import("quasar")['QTab']
export const QTabs: typeof import("quasar")['QTabs']
export const QTime: typeof import("quasar")['QTime']
export const QTimeline: typeof import("quasar")['QTimeline']
export const QTimelineEntry: typeof import("quasar")['QTimelineEntry']
export const QToggle: typeof import("quasar")['QToggle']
export const QToolbar: typeof import("quasar")['QToolbar']
export const QToolbarTitle: typeof import("quasar")['QToolbarTitle']
export const QTooltip: typeof import("quasar")['QTooltip']
export const QTree: typeof import("quasar")['QTree']
export const QUploader: typeof import("quasar")['QUploader']
export const QUploaderAddTrigger: typeof import("quasar")['QUploaderAddTrigger']
export const QVideo: typeof import("quasar")['QVideo']
export const QVirtualScroll: typeof import("quasar")['QVirtualScroll']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyEssentialLink: typeof import("../components/EssentialLink.vue")['default']
export const LazyExampleComponent: typeof import("../components/ExampleComponent.vue")['default']
export const LazyExampleList: typeof import("../components/ExampleList.vue")['default']
export const LazyMenuRedirect: typeof import("../components/MenuRedirect.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyQAjaxBar: typeof import("quasar")['QAjaxBar']
export const LazyQAvatar: typeof import("quasar")['QAvatar']
export const LazyQBadge: typeof import("quasar")['QBadge']
export const LazyQBanner: typeof import("quasar")['QBanner']
export const LazyQBar: typeof import("quasar")['QBar']
export const LazyQBreadcrumbs: typeof import("quasar")['QBreadcrumbs']
export const LazyQBreadcrumbsEl: typeof import("quasar")['QBreadcrumbsEl']
export const LazyQBtn: typeof import("quasar")['QBtn']
export const LazyQBtnDropdown: typeof import("quasar")['QBtnDropdown']
export const LazyQBtnGroup: typeof import("quasar")['QBtnGroup']
export const LazyQBtnToggle: typeof import("quasar")['QBtnToggle']
export const LazyQCard: typeof import("quasar")['QCard']
export const LazyQCardActions: typeof import("quasar")['QCardActions']
export const LazyQCardSection: typeof import("quasar")['QCardSection']
export const LazyQCarousel: typeof import("quasar")['QCarousel']
export const LazyQCarouselControl: typeof import("quasar")['QCarouselControl']
export const LazyQCarouselSlide: typeof import("quasar")['QCarouselSlide']
export const LazyQChatMessage: typeof import("quasar")['QChatMessage']
export const LazyQCheckbox: typeof import("quasar")['QCheckbox']
export const LazyQChip: typeof import("quasar")['QChip']
export const LazyQCircularProgress: typeof import("quasar")['QCircularProgress']
export const LazyQColor: typeof import("quasar")['QColor']
export const LazyQDate: typeof import("quasar")['QDate']
export const LazyQDialog: typeof import("quasar")['QDialog']
export const LazyQDrawer: typeof import("quasar")['QDrawer']
export const LazyQEditor: typeof import("quasar")['QEditor']
export const LazyQExpansionItem: typeof import("quasar")['QExpansionItem']
export const LazyQFab: typeof import("quasar")['QFab']
export const LazyQFabAction: typeof import("quasar")['QFabAction']
export const LazyQField: typeof import("quasar")['QField']
export const LazyQFile: typeof import("quasar")['QFile']
export const LazyQFooter: typeof import("quasar")['QFooter']
export const LazyQForm: typeof import("quasar")['QForm']
export const LazyQFormChildMixin: typeof import("quasar")['QFormChildMixin']
export const LazyQHeader: typeof import("quasar")['QHeader']
export const LazyQIcon: typeof import("quasar")['QIcon']
export const LazyQImg: typeof import("quasar")['QImg']
export const LazyQInfiniteScroll: typeof import("quasar")['QInfiniteScroll']
export const LazyQInnerLoading: typeof import("quasar")['QInnerLoading']
export const LazyQInput: typeof import("quasar")['QInput']
export const LazyQIntersection: typeof import("quasar")['QIntersection']
export const LazyQItem: typeof import("quasar")['QItem']
export const LazyQItemLabel: typeof import("quasar")['QItemLabel']
export const LazyQItemSection: typeof import("quasar")['QItemSection']
export const LazyQList: typeof import("quasar")['QList']
export const LazyQKnob: typeof import("quasar")['QKnob']
export const LazyQLayout: typeof import("quasar")['QLayout']
export const LazyQLinearProgress: typeof import("quasar")['QLinearProgress']
export const LazyQMarkupTable: typeof import("quasar")['QMarkupTable']
export const LazyQMenu: typeof import("quasar")['QMenu']
export const LazyQNoSsr: typeof import("quasar")['QNoSsr']
export const LazyQOptionGroup: typeof import("quasar")['QOptionGroup']
export const LazyQPage: typeof import("quasar")['QPage']
export const LazyQPageContainer: typeof import("quasar")['QPageContainer']
export const LazyQPageScroller: typeof import("quasar")['QPageScroller']
export const LazyQPageSticky: typeof import("quasar")['QPageSticky']
export const LazyQPagination: typeof import("quasar")['QPagination']
export const LazyQParallax: typeof import("quasar")['QParallax']
export const LazyQPopupEdit: typeof import("quasar")['QPopupEdit']
export const LazyQPopupProxy: typeof import("quasar")['QPopupProxy']
export const LazyQPullToRefresh: typeof import("quasar")['QPullToRefresh']
export const LazyQRadio: typeof import("quasar")['QRadio']
export const LazyQRange: typeof import("quasar")['QRange']
export const LazyQRating: typeof import("quasar")['QRating']
export const LazyQResizeObserver: typeof import("quasar")['QResizeObserver']
export const LazyQResponsive: typeof import("quasar")['QResponsive']
export const LazyQScrollArea: typeof import("quasar")['QScrollArea']
export const LazyQScrollObserver: typeof import("quasar")['QScrollObserver']
export const LazyQSelect: typeof import("quasar")['QSelect']
export const LazyQSeparator: typeof import("quasar")['QSeparator']
export const LazyQSkeleton: typeof import("quasar")['QSkeleton']
export const LazyQSlideItem: typeof import("quasar")['QSlideItem']
export const LazyQSlideTransition: typeof import("quasar")['QSlideTransition']
export const LazyQSlider: typeof import("quasar")['QSlider']
export const LazyQSpace: typeof import("quasar")['QSpace']
export const LazyQSpinner: typeof import("quasar")['QSpinner']
export const LazyQSpinnerAudio: typeof import("quasar")['QSpinnerAudio']
export const LazyQSpinnerBall: typeof import("quasar")['QSpinnerBall']
export const LazyQSpinnerBars: typeof import("quasar")['QSpinnerBars']
export const LazyQSpinnerBox: typeof import("quasar")['QSpinnerBox']
export const LazyQSpinnerClock: typeof import("quasar")['QSpinnerClock']
export const LazyQSpinnerComment: typeof import("quasar")['QSpinnerComment']
export const LazyQSpinnerCube: typeof import("quasar")['QSpinnerCube']
export const LazyQSpinnerDots: typeof import("quasar")['QSpinnerDots']
export const LazyQSpinnerFacebook: typeof import("quasar")['QSpinnerFacebook']
export const LazyQSpinnerGears: typeof import("quasar")['QSpinnerGears']
export const LazyQSpinnerGrid: typeof import("quasar")['QSpinnerGrid']
export const LazyQSpinnerHearts: typeof import("quasar")['QSpinnerHearts']
export const LazyQSpinnerHourglass: typeof import("quasar")['QSpinnerHourglass']
export const LazyQSpinnerInfinity: typeof import("quasar")['QSpinnerInfinity']
export const LazyQSpinnerIos: typeof import("quasar")['QSpinnerIos']
export const LazyQSpinnerOrbit: typeof import("quasar")['QSpinnerOrbit']
export const LazyQSpinnerOval: typeof import("quasar")['QSpinnerOval']
export const LazyQSpinnerPie: typeof import("quasar")['QSpinnerPie']
export const LazyQSpinnerPuff: typeof import("quasar")['QSpinnerPuff']
export const LazyQSpinnerRadio: typeof import("quasar")['QSpinnerRadio']
export const LazyQSpinnerRings: typeof import("quasar")['QSpinnerRings']
export const LazyQSpinnerTail: typeof import("quasar")['QSpinnerTail']
export const LazyQSplitter: typeof import("quasar")['QSplitter']
export const LazyQStep: typeof import("quasar")['QStep']
export const LazyQStepper: typeof import("quasar")['QStepper']
export const LazyQStepperNavigation: typeof import("quasar")['QStepperNavigation']
export const LazyQTabPanel: typeof import("quasar")['QTabPanel']
export const LazyQTabPanels: typeof import("quasar")['QTabPanels']
export const LazyQTable: typeof import("quasar")['QTable']
export const LazyQTd: typeof import("quasar")['QTd']
export const LazyQTh: typeof import("quasar")['QTh']
export const LazyQTr: typeof import("quasar")['QTr']
export const LazyQRouteTab: typeof import("quasar")['QRouteTab']
export const LazyQTab: typeof import("quasar")['QTab']
export const LazyQTabs: typeof import("quasar")['QTabs']
export const LazyQTime: typeof import("quasar")['QTime']
export const LazyQTimeline: typeof import("quasar")['QTimeline']
export const LazyQTimelineEntry: typeof import("quasar")['QTimelineEntry']
export const LazyQToggle: typeof import("quasar")['QToggle']
export const LazyQToolbar: typeof import("quasar")['QToolbar']
export const LazyQToolbarTitle: typeof import("quasar")['QToolbarTitle']
export const LazyQTooltip: typeof import("quasar")['QTooltip']
export const LazyQTree: typeof import("quasar")['QTree']
export const LazyQUploader: typeof import("quasar")['QUploader']
export const LazyQUploaderAddTrigger: typeof import("quasar")['QUploaderAddTrigger']
export const LazyQVideo: typeof import("quasar")['QVideo']
export const LazyQVirtualScroll: typeof import("quasar")['QVirtualScroll']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
